### ISSUE TITLE
Needed to create help directory to succeed

### ISSUE THREAD

**Issue by dfinke** [ChaseFlorell/psDoc#4]
Excellent piece of work sir!

Stalled on this, guessed to create the `help` directory, reran and it worked.

```
out-file : Could not find a part of the path 'C:\Users\dfinke\Downloads\psDoc-master\src\help\index.html'.
At C:\Users\dfinke\Downloads\psDoc-master\src\psDoc.ps1:54 char:1
+ Invoke-Expression $template > "$outputDir\$fileName"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

**Comment by ChaseFlorell** [comment]
Yes, currently the `$outputDir` must first exist. It's to be sure that you're dropping the files in the location of your choosing.

Alternatively, you can change the directory with a parameter.

`.\psDoc.ps1 -moduleName MySpecialModule -outputDir 'c:\some\special\path'`

[Here's the one-liner](https://github.com/ChaseFlorell/psDoc/blob/master/src/psDoc.ps1#L54) where it's all coming together.

**Comment by dotps1** [comment]
you could do a

``` powershell
if (-not (Test-path -Path (Split-Path -Path $output -Parent))) {
    try {
        New-Item -Path (Split-Path $output -Parent) -ItemType Directory -ErrorAction Stop
    } catch {
        Write-Error -Message $Error[0].ToString() -ErrorAction Stop
    }
}
```

rather then having to open and debug your code to see why its failing, and so you could do `.\psDoc -ModuleName MySpecialModule`

or better yet, get the Module Invocation and put it there.

just my two cents, looks really good after I got the output.

_Edit_
also I would have the output be called `MySPecialModule.html` so ive you do more then one, it doesn't overwrite.

**Comment by ChaseFlorell** [comment]
It's named index.html so that it can be directly dumped to some web server and update automatically. 
For our purposes, we automatically create it to be uploaded to github pages  
https://futurestatemobile.github.io/poshBAR/ 

The parameters are there for your customization, and at the time I built it, I had a reason for not creating the directory automatically, but I can't remember why.

**Comment by dotps1** [comment]
Index makes sense.

**Comment by ChaseFlorell** [comment]
This could also be a quick way to tackle it. (untested)

```
New-Item $outputDir -ItemType directory -ea SilentlyContinue
Invoke-Expression $template > "$outputDir\$fileName"
```
